services:
  # grpc-app-server:
  #   build:
  #     dockerfile: dev.Dockerfile
  #     context: .
  #   networks:
  #     - grpc-app-network
  #   ports:
  #     - "8081:8081"
  #     - "50051:50051"
  #   expose:
  #     - "8081"
  #     - "50051"
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: personal
      POSTGRES_PASSWORD: words
      POSTGRES_DB: personal-words
    ports:
      - "5432:5432"

networks:
  grpc-app-network:
    driver: bridge
