apiVersion: apps/v1
kind: Deployment
metadata:
  name: vos-personal-words
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vos-personal-words
  template:
    metadata:
      labels:
        app: vos-personal-words
    spec:
      containers:
        - image: mohammaddocker/vos-personal-words
          name: vos-personal-words
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 400m
              memory: 800Mi
          env:  
            - name: PORT
              value: "3000"
          envFrom:
            - secretRef:
                name: managed-secret-server