apiVersion: batch/v1
kind: Job
metadata:
  name: vos-personal-words-migration-job
  annotations:
    argocd.argoproj.io/synchronization: Exclude
spec:
  template:
    spec:
      containers:
        - name: vos-personal-words-migration
          image: mohammaddocker/vos-personal-words
          args: ["migrate"]
          envFrom:
            - secretRef:
                name: managed-personal-words-secret
      restartPolicy: Never
