apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voc-on-steroid

resources:
  - deployment.yml
  - secret.yml
  - service.yml
  - job.yml

images:
  - name: mohammaddocker/vos-personal-words
    newTag: 0.4.5
