apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: vos-template-secret
  annotations:
    argocd.argoproj.io/synchronization: Exclude
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.vault.svc.cluster.local:8080/api

  authentication:
    # Make sure to only have 1 authentication method defined, serviceToken/universalAuth.
    # If you have multiple authentication methods defined, it may cause issues.

    # Universal Auth
    universalAuth:
      secretsScope:
        projectSlug: voc-on-steroid-b9fb
        envSlug: prod # "dev", "staging", "prod", etc..
        secretsPath: "/personal-words" # Root is "/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: vault

  managedSecretReference:
    secretName: managed-personal-words-secret
    secretNamespace: voc-on-steroid
    creationPolicy: "Orphan" ## Owner | Orphan
