apiVersion: v1
kind: Service
metadata:
  name: vos-template-service
spec:
  selector:
    app: vos-template # Match labels from the deployments
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
  clusterIP: None