apiVersion: batch/v1
kind: Job
metadata:
  name: vos-template-migration-job
  annotations:
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: vos-template-migration
          image: mohammaddocker/vos-template
          args: ["migrate"]
          envFrom:
            - secretRef:
                name: managed-personal-words-secret
      restartPolicy: Never
