name: Migrate

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: k8s/migration
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'main'

      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@v2.0.0

      - uses: imranismail/setup-kustomize@v2

      - name: Update kustomize image version
        run: |
          kustomize edit set image ${{ env.IMAGE_NAME }}:${{ steps.info.outputs.version }}

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: git push
        run: |
          git add .
          git commit -m "Chore: update migration image version to ${{ steps.info.outputs.version }}"
          git push